version: '3.7'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8015"
    ports:
      - 8015:8015
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment: # Change secret key, django recomends at least 50 chars
      - SECRET_KEY="X$ydb*Yk&7-26_5pzmmTrdmcVy!cSTk5eF2-E#Gy@R^mG7e295Zdka" 
      - DEBUG=1 # if you are running in debug change it to 1 
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=Un6MZ_^dPmAjcF6? #Change Password
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=Un6MZ_^dPmAjcF6? #Change Password
