# Generated by Django 2.2.10 on 2021-07-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yara_parser', '0003_auto_20210729_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_scan',
            name='analyst_comment',
            field=models.TextField(null=True),
        ),
    ]
