# Generated by Django 2.2.10 on 2021-07-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yara_parser', '0004_file_scan_analyst_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_scan',
            name='analyst_comment',
            field=models.TextField(null=True),
        ),
    ]
