# Generated by Django 2.2.10 on 2021-08-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yara_parser', '0005_process_scan_analyst_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='scans',
            name='scan_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
