# Generated by Django 2.2.10 on 2021-08-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yara_parser', '0006_scans_scan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.TextField()),
                ('ip_add', models.TextField()),
                ('mac_add', models.TextField()),
                ('os', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
