# Generated by Django 2.2.10 on 2021-08-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yara_parser', '0007_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='policy_scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('path', models.TextField()),
                ('descreption', models.TextField()),
            ],
        ),
    ]
