# Generated by Django 2.2.10 on 2021-08-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yara_parser', '0008_policy_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy_scan',
            name='link',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
