# Generated by Django 2.2.10 on 2021-08-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yara_parser', '0010_auto_20210831_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
