# Generated by Django 2.2.10 on 2021-08-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yara_parser', '0011_auto_20210831_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedualled_scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.TextField()),
                ('target_machine', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
