# Generated by Django 2.2.10 on 2021-08-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yara_parser', '0012_schedualled_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedualled_scan',
            name='target_mac',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
